# Generated by Django 4.2.5 on 2023-09-21 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='RNBQKBNRPPPPPPPP00000000000000000000000000000000pppppppprnbkqbnr', max_length=64, validators=[django.core.validators.RegexValidator('[kqpbr0]{64}', flags=re.RegexFlag['IGNORECASE'])])),
                ('moveCount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5949)])),
                ('moves', models.TextField(max_length=29745)),
                ('status', models.SmallIntegerField(choices=[(1, 'WAITING_FOR_OPPONENT'), (2, 'ACTIVE'), (3, 'PAUSED'), (4, 'COMPLETE')])),
                ('outcome', models.SmallIntegerField(blank=None, choices=[(1, 'WHITE_WON'), (2, 'BLACK_WON'), (3, 'DRAW'), (4, 'WHITE_FORFEIT'), (5, 'BLACK_FORFEIT')], null=None)),
                ('playerBlack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_black_1', to='chess.player')),
                ('playerWhite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_white_1', to='chess.player')),
            ],
        ),
    ]
