# Generated by Django 4.2.5 on 2023-09-22 17:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    replaces = [('chess', '0001_initial'), ('chess', '0002_remove_chessgame_playerblack_and_more'), ('chess', '0003_alter_friend_createdate_alter_player_createdate')]

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.authuser')),
                ('archive', models.BooleanField(default=False)),
                ('createDate', models.DateField(default=datetime.datetime(2023, 9, 22, 17, 4, 8, 792648, tzinfo=datetime.timezone.utc))),
                ('rank', models.IntegerField(default=1200, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(400)])),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='RNBQKBNRPPPPPPPP00000000000000000000000000000000pppppppprnbkqbnr', max_length=64, validators=[django.core.validators.RegexValidator('[kqpbr0]{64}', flags=re.RegexFlag['IGNORECASE'])])),
                ('moveCount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5949)])),
                ('moves', models.TextField(default='', max_length=29745)),
                ('status', models.SmallIntegerField(choices=[(1, 'WAITING_FOR_OPPONENT'), (2, 'PENDING_MATCH_ACCEPTED'), (3, 'MATCH_DECLINED'), (4, 'ACTIVE'), (5, 'PAUSED'), (6, 'COMPLETE')])),
                ('outcome', models.SmallIntegerField(blank=None, choices=[(1, 'WHITE_WON'), (2, 'BLACK_WON'), (3, 'DRAW'), (4, 'WHITE_FORFEIT'), (5, 'BLACK_FORFEIT')], null=None)),
                ('defaultSides', models.BooleanField(default=True)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_opponent_1', to='chess.player')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_owner_1', to='chess.player')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend_requestee', to='chess.player')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend_requester', to='chess.player')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(default=datetime.datetime(2023, 9, 22, 17, 4, 8, 792980, tzinfo=datetime.timezone.utc))),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend1', to='chess.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend2', to='chess.player')),
            ],
        ),
    ]
