# Generated by Django 4.2.5 on 2023-09-22 17:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='playerBlack',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='playerWhite',
        ),
        migrations.AddField(
            model_name='chessgame',
            name='defaultSides',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_opponent_1', to='chess.player'),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_game_player_owner_1', to='chess.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 17, 2, 46, 975642)),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=1200, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='moveCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5949)]),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='moves',
            field=models.TextField(default='', max_length=29745),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'WAITING_FOR_OPPONENT'), (2, 'PENDING_MATCH_ACCEPTED'), (3, 'MATCH_DECLINED'), (4, 'ACTIVE'), (5, 'PAUSED'), (6, 'COMPLETE')]),
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend_requestee', to='chess.player')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend_requester', to='chess.player')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(default=datetime.datetime(2023, 9, 22, 17, 2, 46, 975816))),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend1', to='chess.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_player_friend2', to='chess.player')),
            ],
        ),
    ]
