# Generated by Django 4.2.5 on 2023-09-22 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_remove_chessgame_playerblack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 17, 4, 8, 792980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='createDate',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 17, 4, 8, 792648, tzinfo=datetime.timezone.utc)),
        ),
    ]
